### ISSUE TITLE
Database is not automatically set when dockerize the db server and run it

### ISSUE THREAD

**Issue by JacobYim** [JacobYim/CSE442-BuyNSell#26]
Database is not automatically set when dockerize the db server and run it. Please check about the docker.

**Comment by JacobYim** [comment]
The problem has been solved by following updates :

`docker-compose.yml` 
```
version: "3"
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=buynsell
    volumes:
      - ./db/database.sql:/docker-entrypoint-initdb.d/dump.sql
    ports:
      - 5432:5432
    restart: always
  buynsell: 
    image: buynsell
    ports: 
      - 8080:8080
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; npm start'
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/buynsell
      - PORT=3000
```
PostgresSQL is initialized by executing the .sql file in  the `docker-entrypoint-initdb.d` directory. So, share `database.sql` file though the volumes of the Docker.
